### ISSUE TITLE
'Digital: A Love Story' not launching on Fedora 26

### ISSUE THREAD

**Issue by HoboPrimate** [flathub/com.scoutshonour.Digital#3] opened 2017-08-22 20:42 UTC
> $ flatpak run com.scoutshonour.Digital
> /app/lib/python: line 23: /app/lib/linux-x86/python.real: No such file or directory
> /app/lib/python: line 23: /app/lib/linux-iliad/python.real: No such file or directory
> Could not find a python that runs on your platform. Sorry.

Installed on Fedora 26 with Gnome Software.
Flatpak 0.9.7

**Comment by marcosps** [comment] 2017-09-18 23:35
Same here with 0.9.12 on Fedora 26

**Comment by TingPing** [comment] 2017-09-19 00:33
Maybe this is a duplicate of #2 ?

Does this work:

```
flatpak uninstall com.scoutshonour.Digital
flatpak install flathub com.scoutshonour.Digital/i386/stable
flatpak run com.scoutshonour.Digital
```

**Comment by marcosps** [comment] 2017-09-19 00:54
@TingPing yes, this solves the problem. So, there is some problem with the python version of the x64 runtime?

**Comment by TingPing** [comment] 2017-09-19 01:00
No the game just doesn't have a 64bit version. Closing this since its a duplicate.

**Closed by TingPing** 2017-09-19 01:00 UTC

**Comment by marcosps** [comment] 2017-09-19 01:03
Is there a way to specify the 32bit version in the flatpakref file, so the user don't get confused about it?

**Comment by TingPing** [comment] 2017-09-19 01:09
This is just an issue with flathubs repository containing invalid data, it should get resolved.

**Comment by marcosps** [comment] 2017-09-19 01:09
Fair enough, thanks!
