### ISSUE TITLE
does not open

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.scoutshonour.Digital#5] opened 2017-12-03 13:10 UTC
[eos-diagnostic-171203_110946_UTC-0200.txt](https://github.com/flathub/com.scoutshonour.Digital/files/1524756/eos-diagnostic-171203_110946_UTC-0200.txt)

/app/lib/python: line 23: /app/lib/linux-x86/python.real: No such file or directory
/app/lib/python: line 23: /app/lib/linux-iliad/python.real: No such file or directory
Could not find a python that runs on your platform. Sorry.

**Comment by LeandroStanger** [comment] 2017-12-03 13:10
@nedrichards Could help

**Comment by TingPing** [comment] 2017-12-03 14:35
Duplicate of #2

**Closed by TingPing** 2017-12-03 14:35 UTC
